### ISSUE TITLE
Query Bean new QCustomer().id is null

### ISSUE THREAD

**Issue by ooknight** [ebean-orm/querybean-generator#17]
I follow ebean-orm-examples/example-minimal.git, querybean works well,
but when i upgrade querybean-generator to 11.1.1, new QCustomer().id is null,
and use ebean-maven-plugin and querybean-maven-plugin also is null.
How can I make querybean work use the highest version of ebean and ebean-maven-plugin ?
Thank you !

**Comment by rbygrave** [comment]
Hi,
Ok, sorry I missed this. Note that in general it is better to ask questions on the Ebean forum ... https://groups.google.com/forum/#!forum/ebean

Your question will go to more people and it won't get forgotton if you ask it there.

As for the issue, yes I need to update the dependencies on the example ... I'll see if I can do that over the weekend.

Cheers, Rob.

**Comment by rbygrave** [comment]
I have updated both the `minimal` and example-java8 which is at https://github.com/ebean-orm-examples/example-java8

Note that the example-java8 ... has the QueryBean generation etc.

Cheers, Rob.

**Comment by rbygrave** [comment]
Ok, updated the minimal with query bean support.

To add query bean support ... 
- Make sure we have a ebean.mf ... with the querybean-packages specified
- Modify the pom adding the dependency for ebean-querybean and querybean-generator (provided)

See https://github.com/ebean-orm-examples/example-minimal/commit/a535f8c85387c7ba811611a72d541a83e0550e63

Cheers, Rob.

**Comment by rbygrave** [comment]
I'll close this now.
