### ISSUE TITLE
Enum field with @NotNull causes generated Qxxx.class error.

### ISSUE THREAD

**Issue by 54446776** [ebean-orm/querybean-generator#20]
Can repeat with the latest example-java8 project. Just try to add @NotNull annotation with status field in Order class, then compilation happen.

**Comment by rbygrave** [comment]
> Just try to add @NotNull annotation with status field in Order class

Made that change - no issue, no exception, all working fine.

Please update with details that reproduce the error and include the compilation error or close this issue.

Thanks, Rob.

**Comment by 54446776** [comment]
Use javax.validation.constraints.NotNull cause error:
[ERROR] /Users/xxx/IdeaProjects/example-java8/target/generated-sources/annotations/org/example/domain/query/QOrder.java:[3,7] <identifier> expected
[ERROR] /Users/xxx/IdeaProjects/example-java8/target/generated-sources/annotations/org/example/domain/query/QOrder.java:[3,9] <identifier> expected
....
....

User io.ebean.annotation.NotNull no problem.

I was confused for a long time, which NotNull should I use.

**Comment by rbygrave** [comment]
Ah right.  Cool, found and fixed - thanks.
