### ISSUE TITLE
Properties override duplication

### ISSUE THREAD

**Issue by tyan-boot** [ebean-orm/querybean-generator#30]
When have this
```kotlin
@MappedSuperclass
open class BaseModel: Model() {
  @Id
  open var id: Long = 0
...
}
```
and a derived model which override id property :
```kotlin
@Entity
class Derived : BaseModel() {
  @Id
  @Column(name = "...")
  override var id: Long = 0
...
}
```

Then the generated `QDerived` will have two id property like this

```kotlin
@TypeQueryBean
class QDerived : TQRootBean<Derived, QDerived> {
  ...
  lateinit var id: PLong<QDerived>
  lateinit var id: PLong<QDerived>
  ...
}
```

**Comment by rbygrave** [comment]
> and a derived model which override id property :

I don't think this is particularly "good" or "correct" in terms of byte code as in it looks like this results in `field hiding` to me.  Instead, I think you should instead be using `@AttributeOverride` to override the column name.

Have you checked the byte code for "field hiding"?
Have you tried using  `@AttributeOverride` instead?

**Comment by rbygrave** [comment]
Are you happy with `@AttributeOverride` ?

**Comment by tyan-boot** [comment]
Sorry for reply so late. I found this issue was submitted to a wrong repo, it should be transferred to `kotlin-querybean-generator`. Kotlin allow properties override, but it also seems to have filed hiding problem in byte code.

`@AttributeOverride` works fine to me.

**Comment by rbygrave** [comment]
Cool - closing for now then ... with the thought that we should use `@AttributeOverride` but maybe need to take a closer look at Kotlin property overrides (bytecode).
