### ISSUE TITLE
java.io.IOException: line too long when entity-packages in ebean-generated-info.mf greater than 512byte

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm/querybean-generator#48]
Error reading manifest resources file:/Users/spinach/Documents/IdeaProject/git/combatplatform/target/classes/META-INF/ebean-generated-info.mf
java.io.IOException: line too long
I read the jdk source ，in java.util.jar.Attributes.read method,the read buffer is default 512k .gt 512 one line in the mf file will throw upper Exception

**Comment by rbygrave** [comment]
Fixed by PR #49
