### ISSUE TITLE
Package of generated ModuleInfo class is "unknown"

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/querybean-generator#50]
All of our entities are in the same package and the base entity has `@DbName` annotation.

Looking at https://github.com/ebean-orm/querybean-generator/blob/91b27579c247ad9d4931731468497e40cbaf4efb/src/main/java/io/ebean/querybean/generator/ProcessingContext.java#L382
it seems that the `factoryPackage` will never be updated if all entities have a `@DbName` associated.

I think 
https://github.com/ebean-orm/querybean-generator/blob/91b27579c247ad9d4931731468497e40cbaf4efb/src/main/java/io/ebean/querybean/generator/ProcessingContext.java#L395
should be moved out of the `else` block.

Also what happens if entities are in multiple packages? Looks like one of these packages will be selected then. Maybe it is better to have a fixed but configurable package or generate multiple `_ebean$ModuleInfo` classes, one per entity package stored in that package.

**Comment by rbygrave** [comment]
> Also what happens if entities are in multiple packages?

The shortest length package name wins.

> Maybe it is better to ... generate multiple _ebean$ModuleInfo classes

Maybe - one per unique DbName would make sense.  I'll fix this by moving the updateFactoryPackage() call but we can keep that idea in mind as a potential better approach down the track.
