### ISSUE TITLE
javac annotationprocessor problem with static imports

### ISSUE THREAD

**Issue by turbospaces** [ebean-orm/querybean-generator#52]
Latest version of query-bean generator is not executed as part of maven build (annotation processing is not happening). 

I have spent half a day troubleshooting root cause and i guess it's very similar to https://github.com/rzwitserloot/lombok/issues/1722

Static imports were added recently https://github.com/ebean-orm/querybean-generator/commit/79c7f4c81de6d16a40e44eb04af637d9c8f2bbad 

I suggest to remove all static imports as such in this project.

BTW - this generator works in some cases, in some not. This might be useful

For some reason, javac tries to resolve static imports too early in the process. This causes an error, IIRC already during parsing. And if an error exists in that phase, the annotation processors are not triggered at all. None of them. So lombok does not get a chance to generate the code, or give a better error message.

**Comment by turbospaces** [comment]
@rbygrave  - reverted query-bean generator to 12.1.10 and annotation processor is being executed, so there is some wrong in between those 2 versions

**Comment by rbygrave** [comment]
Hi @turbospaces - we have released version 12.2.2 of querybean-generator with all the `import static` removed. Do you want to try that and confirm that was the issue?

Thanks, Rob.

**Comment by turbospaces** [comment]
@rbygrave - tried, it works as expected.  thx for quick fix
