### ISSUE TITLE
query-bean generator doesn't work again on JDK11

### ISSUE THREAD

**Issue by turbospaces** [ebean-orm/querybean-generator#54]
I have following dependency

```
<dependency>
        <groupId>io.ebean</groupId>
        <artifactId>querybean-generator</artifactId>
        <scope>provided</scope>
       <version>12.2.6</version>
 </dependency>
```
ebean version is **12.1.13**. It works under java8/11.

Any attempt to upgrade ebean to higher version lead to no generator execution under java 11 as such. there are no errors, nothing. Strangely, but it still works with latest version of ebean/generator under java8.

What could be the reason? JDK 11 users are blocked in upgrade higher than 12.1.13.

BR,
Andrey

**Comment by rbygrave** [comment]
Not sure.  Can you provide a full example of what does not work?  Have you
tried the newly released 12.3.1 of everything?

**Comment by turbospaces** [comment]
just configure any maven project which will use default annotation processing discovery and try to build project. As i mentioned, it start to break when i set core ebean version > 12.1.13
So something happened after that release for sure. Latest version doesn't work

```
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <dependencies>
                        <dependency>
                            <groupId>org.ow2.asm</groupId>
                            <artifactId>asm</artifactId>
                            <version>8.0.1</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <source>11</source>
                        <target>11</target>
                        <release>11</release>
                    </configuration>
                </plugin>
```

**Comment by rbygrave** [comment]
I'm using java 11 all the time with no problem.  Can you create a PR should
it not working for
https://github.com/ebean-orm-examples/example-minimal project
?

Maybe the issue is related to your maven-compiler-plugin including the
dependency for asm ?

**Comment by turbospaces** [comment]
created fresh new project and generator works now, so i presume something happened in between releasees. probably something with ebean.mf? where there any significant changes?

**Comment by turbospaces** [comment]
found the reason. properties were renamed for some reason to
```
x-entity-packages
x-querybean-packages
```
